import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Bot Configuration
BOT_TOKEN = os.getenv("BOT_TOKEN")
ADMIN_ID = os.getenv("ADMIN_ID")

# Supabase Configuration
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

# Web App Configuration
WEBAPP_URL = "http://localhost:8000"

# Game Settings
SPIN_COST = 25  # Cost in stars to spin the roulette
GIFTS = [
    {"name": "⭐️ 15 Stars", "value": 15, "weight": 100},  # 100% chance
    {"name": "⭐️ 25 Stars", "value": 25, "weight": 0},
    {"name": "⭐️ 35 Stars", "value": 35, "weight": 0},
    {"name": "⭐️ 50 Stars", "value": 50, "weight": 0},
    {"name": "⭐️ 100 Stars", "value": 100, "weight": 0},
    {"name": "⭐️ 250 Stars", "value": 250, "weight": 0}
]

# Database Tables SQL
DATABASE_TABLES = """
-- Users table with extended statistics
create table if not exists users (
    user_id bigint primary key,
    username text,
    stars integer default 0,
    total_games integer default 0,
    total_won integer default 0,
    biggest_win integer default 0,
    total_spent integer default 0,
    last_spin timestamp with time zone,
    created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Transactions table with more details
create table if not exists transactions (
    id bigint generated by default as identity primary key,
    user_id bigint references users(user_id),
    amount integer,
    type text,
    gift_value integer,
    timestamp timestamp with time zone default timezone('utc'::text, now())
);

-- Leaderboard view
create or replace view leaderboard as
select 
    user_id,
    username,
    stars,
    total_games,
    total_won,
    biggest_win,
    total_spent,
    (total_won - total_spent) as net_profit
from users
order by stars desc, total_won desc
limit 100;
"""

# Messages
WELCOME_MESSAGE = """
🎰 Добро пожаловать в игровую рулетку!

Испытайте удачу и получите редкий подарок! 
Стоимость одного вращения: {} ⭐️

Возможные подарки:
• {} (Всегда)
• {} (Редко)
• {} (Очень редко)
• {} (Супер редко)
• {} (Мега редко)
• {} (Легендарно)

Нажмите кнопку "Испытать удачу!" чтобы начать!
""".format(SPIN_COST, GIFTS[0]["name"], GIFTS[1]["name"], GIFTS[2]["name"], 
           GIFTS[3]["name"], GIFTS[4]["name"], GIFTS[5]["name"])

SPIN_REQUEST_MESSAGE = "💫 Для вращения рулетки, пожалуйста, отправьте {} ⭐️"
INSUFFICIENT_FUNDS = "❌ У вас недостаточно звезд! Необходимо {} ⭐️"
SPINNING_MESSAGE = "🎰 Крутим рулетку..."
WIN_MESSAGE = "🎉 Вам выпало: {}\nЧто хотите сделать с подарком?"
SOLD_MESSAGE = "💰 Вы продали подарок и получили {} ⭐️"
KEPT_MESSAGE = "✨ Вы оставили себе {} ⭐️"

# Database settings
DATABASE_FILE = "bot_database.db" 